service-jenkins-panel:
  build: .
  ports:
   - "8000:80"
   - "1984:1984"
  environment:
   - DEBUG=1
   - USE_WDB=1
   - WDB_NO_BROWSER_AUTO_OPEN=1
  volumes:
   - .:/opt/jenkins_panel/repository
  links:
    - service-jenkins-panel-mongo:mongo
service-jenkins-panel-mongo:
  image: mongo
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password
   - MYSQL_DATABASE=jenkins_panel